---
- name: "Download"
  get_url:
    url: "{{ download_url }}"
    dest: "{{ executable_location }}"
    mode: 0755
  notify: "restart fabio service"

- name: "Preparing config dir"
  file:
    state: directory
    path: "{{ config_dir }}"

- name: "Setting systemd service"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "templates/fabio.service",
        dest: "/etc/systemd/system/fabio.service"
      }
    - {
        src: "templates/fabio.properties",
        dest: "{{ config_dir }}/fabio.properties"
      }
  notify: "restart fabio service"

- name: "Enabling service"
  service:
    name: fabio
    enabled: yes
  notify: "restart fabio service"

